### ISSUE TITLE
Problem: reindex-index-data script sets ingest date as the current one

### ISSUE THREAD

**Issue by scollazo** [artefactual/archivematica-devtools#49] opened 2017-11-23 17:13 UTC
It should be the date the aip was ingested

**Comment by jhsimpson** [comment] 2017-11-30 23:50
I believe this issue is caused by this line of code in archivematicaCommon:

https://github.com/artefactual/archivematica/blob/qa/1.x/src/archivematicaCommon/lib/elasticSearchFunctions.py#L547

Instead of using time.time() , the value should be set to a value found in the AIP METS file, using the CREATEDATE property of the metsHdr

`<mets:mets xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version111/mets.xsd"><mets:metsHdr CREATEDATE="2017-11-30T23:38:39"/>`

This is necessary because aips can be reindexed at some point after they were created, and the ES index should reflect the original date that the AIP was created, not the time the indexing process ran.

**Comment by marktriggs** [comment] 2017-12-04 02:59
Thanks @jhsimpson,

We've had a look at this one too and just wanted to check that we're seeing the same thing.

Looking at the "Date stored" for the AIP in the dashboard here:

http://tsp.nz/s/db9b9c8e1cd329ed3b377861bf42b7217a2b173c.jpg

we didn't see `reindex-index-data` doing anything to change the date, but we did see `rebuild-elasticsearch-aip-index-from-files` reset it to current time.  Digging around, we found `elasticSearchFunctions.py` setting the created date to the mtime of the METS file on disk.  This doesn't work as expected because that METS file is a temporary file, so its mtime will always be moments before.

We've pushed a proposed fix here:

https://github.com/hudmol/archivematica/commit/2f2845e38a3cbd10866eb055426850f40bf191a5

but just wanted to check:

  * Are we talking about the same issue?

  * If so, which archivematica branch should the PR be sent to?  Would that be `dev/1.8.x`?

Thanks!

**Comment by jhsimpson** [comment] 2017-12-05 02:36
Yes, we are talking about the same issue and yes this looks like a good fix.

The qa/1.x branch is effectively the 'master' branch of archivematica.  All dev/ branches are feature branches, that get merged into qa/1.x eventually.  stable/ branches are forked from qa/1.x when we are ready to create a new release.  

We just recently made a stable/1.7.x branch.  I suggest you make a PR against qa/1.x, we might want to merge into stable/1.7.x as well, to fix this bug in the next release.

**Comment by sevein** [comment] 2017-12-15 15:55
Fixed by https://github.com/artefactual/archivematica/pull/824. Thanks @marktriggs.

**Closed** 2018-08-10 17:35 UTC
Labels: Request: help wanted, Type: good first issue
